service: notes-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: simeEdin
  region: eu-north-1
  iam:
    role: arn:aws:iam::239511534325:role/school-role

plugins:
  - serverless-webpack

package:
  individually: true

functions:
  function1:
    handler: index.handler
